import type { PostDocument, UserDocument } from "../types/models.js";

const now = new Date("2026-06-06T09:00:00.000Z");
const daysAgo = (n: number) => new Date(now.getTime() - n * 86_400_000);

export const users: UserDocument[] = [
  {
    handle: "elena_altitude",
    display_name: "Dr. Elena Vasquez",
    role: "Sports Scientist",
    headline: "High-altitude physiology lead — endurance & acclimatisation",
    location: { city: "Mexico City", country: "Mexico", host_city: true },
    coaching_philosophy:
      "Performance at altitude is a problem of oxygen economy, not willpower. I build acclimatisation protocols around live-high/train-low principles, haemoglobin mass tracking, and individualised arterial oxygen saturation thresholds. Every conditioning block is periodised against a measured VO2max decay curve at the target elevation.",
    sportscertify_credentials: {
      verified: true,
      member_since: daysAgo(420),
      specializations: ["Altitude Acclimatisation", "Endurance Conditioning", "Blood Biomarkers"],
      certifications: [
        {
          course_id: "SS-10MOD-ELITE",
          course_title: "Sports Science Certification — Elite Conditioning Track",
          status: "certified",
          modules_completed: 10,
          total_modules: 10,
          certified_on: daysAgo(300),
          credential_uid: "SC-CERT-ELN-0001",
        },
      ],
    },
    follower_count: 18420,
    following_count: 312,
    created_at: daysAgo(420),
  },
  {
    handle: "marco_lowblock",
    display_name: "Marco Bianchi",
    role: "Tactical Analyst",
    headline: "Breaking down low-block defenses & transition moments",
    location: { city: "Toronto", country: "Canada", host_city: true },
    coaching_philosophy:
      "Space is created, not found. I analyse the game as a series of provoked overloads — pinning a back line with a false nine, then attacking the half-spaces the moment a fullback steps. Data only matters when it explains a decision a coach can rehearse on Monday.",
    sportscertify_credentials: {
      verified: true,
      member_since: daysAgo(365),
      specializations: ["Positional Play", "Defensive Structure", "Set-Piece Design"],
      certifications: [
        {
          course_id: "SS-10MOD-TACT",
          course_title: "Sports Science Certification — Tactical Analysis Track",
          status: "completed",
          modules_completed: 10,
          total_modules: 10,
          certified_on: daysAgo(240),
          credential_uid: "SC-CERT-MRC-0002",
        },
      ],
    },
    follower_count: 9650,
    following_count: 540,
    created_at: daysAgo(365),
  },
  {
    handle: "amara_sc",
    display_name: "Amara Okafor",
    role: "Strength & Conditioning Coach",
    headline: "S&C for tournament congestion — managing the 7-game grind",
    location: { city: "Atlanta", country: "USA", host_city: true },
    coaching_philosophy:
      "A World Cup is won in the recovery windows. I treat acute:chronic workload ratio as the single most important guardrail against soft-tissue injury, and I individualise heat-acclimation dosing so players arrive at kickoff with an expanded plasma volume rather than a depleted one.",
    sportscertify_credentials: {
      verified: true,
      member_since: daysAgo(280),
      specializations: ["Load Management", "Heat Acclimation", "Return-to-Play"],
      certifications: [
        {
          course_id: "SS-10MOD-SC",
          course_title: "Sports Science Certification — Strength & Conditioning Track",
          status: "certified",
          modules_completed: 10,
          total_modules: 10,
          certified_on: daysAgo(150),
          credential_uid: "SC-CERT-AMR-0003",
        },
      ],
    },
    follower_count: 12300,
    following_count: 198,
    created_at: daysAgo(280),
  },
  {
    handle: "ref_klaas",
    display_name: "Klaas De Vries",
    role: "FIFA Referee",
    headline: "FIFA International panel — SAOT & match-control standards",
    location: { city: "Amsterdam", country: "Netherlands", host_city: false },
    coaching_philosophy:
      "Consistency is the referee's only currency. I prepare for tournament heat the same way players do — hydration strategy, sprint-recovery between high-tempo phases — because a fatigued official makes late, soft calls. Semi-automated offside technology widens the margin, it does not replace positioning.",
    sportscertify_credentials: {
      verified: true,
      member_since: daysAgo(500),
      specializations: ["Match Control", "Offside Technology", "Officiating Fitness"],
      certifications: [
        {
          course_id: "SS-10MOD-OFF",
          course_title: "Sports Science Certification — Officiating Performance Track",
          status: "certified",
          modules_completed: 9,
          total_modules: 10,
          certified_on: daysAgo(90),
          credential_uid: "SC-CERT-KLS-0004",
        },
      ],
    },
    follower_count: 4200,
    following_count: 76,
    created_at: daysAgo(500),
  },
  {
    handle: "sofia_logistics",
    display_name: "Sofia Hernández",
    role: "Performance Analyst",
    headline: "Travel load & circadian planning across 3-nation venues",
    location: { city: "Guadalajara", country: "Mexico", host_city: true },
    coaching_philosophy:
      "The 2026 tournament is a logistics problem disguised as a football one. Three countries, four time zones, sea-level-to-2,240m altitude swings between matches. I model each squad's travel-induced fatigue and circadian disruption, then hand the medical staff a sleep and light-exposure plan per fixture.",
    sportscertify_credentials: {
      verified: true,
      member_since: daysAgo(210),
      specializations: ["Travel Load", "Circadian Planning", "Match Scheduling Analytics"],
      certifications: [
        {
          course_id: "SS-10MOD-ANL",
          course_title: "Sports Science Certification — Performance Analytics Track",
          status: "in_progress",
          modules_completed: 7,
          total_modules: 10,
          certified_on: null,
          credential_uid: "SC-CERT-SFA-0005",
        },
      ],
    },
    follower_count: 7800,
    following_count: 410,
    created_at: daysAgo(210),
  },
  {
    handle: "coach_lindqvist",
    display_name: "Erik Lindqvist",
    role: "Head Coach",
    headline: "Pressing systems & in-possession structure — national team",
    location: { city: "Stockholm", country: "Sweden", host_city: false },
    coaching_philosophy:
      "I want my team to defend with the ball. Our pressing triggers are rehearsed to the point of reflex, and our build-up exists to bait the press, not to avoid it. Conditioning serves the idea: if the players can't sustain a 4-second counter-press in minute 85, the tactics are fiction.",
    sportscertify_credentials: {
      verified: true,
      member_since: daysAgo(330),
      specializations: ["High Press", "Build-Up Play", "Game Model Design"],
      certifications: [
        {
          course_id: "SS-10MOD-TACT",
          course_title: "Sports Science Certification — Tactical Analysis Track",
          status: "certified",
          modules_completed: 10,
          total_modules: 10,
          certified_on: daysAgo(120),
          credential_uid: "SC-CERT-ERK-0006",
        },
      ],
    },
    follower_count: 15600,
    following_count: 288,
    created_at: daysAgo(330),
  },
];

export const posts: PostDocument[] = [
  {
    slug: "high-altitude-acclimation-mexico-city-2026",
    author_handle: "elena_altitude",
    author_display_name: "Dr. Elena Vasquez",
    author_role: "Sports Scientist",
    post_type: "sports_science_data",
    content:
      "High-altitude acclimation strategies for teams playing in Mexico City (2,240m): arriving 10–14 days early lets haemoglobin mass climb ~3–4%, but the first 72 hours show a measurable VO2max drop of 6–8%. We stagger high-intensity work to protect arterial oxygen saturation and front-load hydration to offset accelerated fluid loss in dry mountain air.",
    tags: ["#WorldCup2026", "#SportsScience", "#AltitudeTraining", "#Endurance"],
    metrics: {
      elevation_m: 2240,
      hb_mass_gain_pct: 3.5,
      vo2max_drop_first72h_pct: 7,
      recommended_arrival_days: 12,
    },
    top_comments: [
      {
        comment_id: "c-001",
        author_handle: "amara_sc",
        author_display_name: "Amara Okafor",
        author_role: "Strength & Conditioning Coach",
        text: "Pairing this with a heat-acclimation block before travel gave us a bigger plasma-volume buffer. Stacking the two adaptations is underrated.",
        likes: 142,
        created_at: daysAgo(2),
      },
      {
        comment_id: "c-002",
        author_handle: "coach_lindqvist",
        author_display_name: "Erik Lindqvist",
        author_role: "Head Coach",
        text: "The 85th-minute counter-press is exactly where altitude punishes you. We're rehearsing shorter press triggers for the Mexico City fixtures.",
        likes: 88,
        created_at: daysAgo(2),
      },
    ],
    like_count: 1840,
    repost_count: 312,
    created_at: daysAgo(3),
  },
  {
    slug: "mbappe-acceleration-analytics-vs-low-block",
    author_handle: "marco_lowblock",
    author_display_name: "Marco Bianchi",
    author_role: "Tactical Analyst",
    post_type: "tactical_analysis",
    content:
      "Mbappé acceleration analytics vs. low-block defenses: against a compact 5-3-2 he barely touches top speed — the value is in his 0–10m burst. Our tracking shows he wins 71% of duels where he attacks the outside shoulder of the widest centre-back within 2.3 seconds of a half-space pass. The counter is a disciplined cover-shadow, not a faster fullback.",
    tags: ["#WorldCup2026", "#TacticalAnalysis", "#LowBlock", "#PlayerData"],
    metrics: {
      first_10m_burst_ms: 1.62,
      duel_win_pct_outside_shoulder: 71,
      avg_decision_window_s: 2.3,
    },
    top_comments: [
      {
        comment_id: "c-003",
        author_handle: "coach_lindqvist",
        author_display_name: "Erik Lindqvist",
        author_role: "Head Coach",
        text: "Cover-shadow over chasing pace — agreed. The mistake is letting the near-side midfielder ball-watch on that half-space entry.",
        likes: 64,
        created_at: daysAgo(1),
      },
    ],
    like_count: 965,
    repost_count: 154,
    created_at: daysAgo(2),
  },
  {
    slug: "managing-player-workload-7-match-world-cup-run",
    author_handle: "amara_sc",
    author_display_name: "Amara Okafor",
    author_role: "Strength & Conditioning Coach",
    post_type: "player_workload",
    content:
      "Managing player physical workload across a 7-match World Cup run: we cap the acute:chronic workload ratio between 0.8 and 1.3, and we treat the third game in a group of three as the highest soft-tissue risk window. Heat management in Atlanta and Dallas matters as much as the altitude conversation — core-temperature creep, not fatigue, is what ends tournaments early.",
    tags: ["#WorldCup2026", "#LoadManagement", "#SportsScience", "#Conditioning"],
    metrics: {
      acwr_lower_bound: 0.8,
      acwr_upper_bound: 1.3,
      highest_risk_match: "Group Match 3",
      target_core_temp_c: 38.5,
    },
    top_comments: [
      {
        comment_id: "c-004",
        author_handle: "elena_altitude",
        author_display_name: "Dr. Elena Vasquez",
        author_role: "Sports Scientist",
        text: "The heat-then-altitude sequencing across venues is the real puzzle. Plasma volume gains from heat help, but you lose some of it within days at elevation.",
        likes: 203,
        created_at: daysAgo(1),
      },
      {
        comment_id: "c-005",
        author_handle: "sofia_logistics",
        author_display_name: "Sofia Hernández",
        author_role: "Performance Analyst",
        text: "And the travel between those venues compounds it. A Dallas→Mexico City turnaround is a circadian and altitude hit in one fixture.",
        likes: 117,
        created_at: daysAgo(1),
      },
    ],
    like_count: 1230,
    repost_count: 221,
    created_at: daysAgo(2),
  },
  {
    slug: "three-nation-world-cup-travel-load-modelling",
    author_handle: "sofia_logistics",
    author_display_name: "Sofia Hernández",
    author_role: "Performance Analyst",
    post_type: "team_logistics",
    content:
      "Team logistics modelling for a three-nation World Cup: the brutal fixtures aren't the hardest opponents, they're the sea-level-to-altitude swings on short rest. A squad playing Houston then Mexico City inside four days absorbs a circadian shift plus a 2,240m elevation jump. We hand staff a per-fixture light-exposure and sleep-banking plan to blunt travel-induced fatigue.",
    tags: ["#WorldCup2026", "#TeamLogistics", "#TravelLoad", "#CircadianPlanning"],
    metrics: {
      max_elevation_swing_m: 2240,
      tightest_turnaround_days: 4,
      time_zones_crossed: 2,
    },
    top_comments: [
      {
        comment_id: "c-006",
        author_handle: "ref_klaas",
        author_display_name: "Klaas De Vries",
        author_role: "FIFA Referee",
        text: "Officials face the same travel grid. We're building recovery protocols between assignments for exactly this reason.",
        likes: 51,
        created_at: daysAgo(1),
      },
    ],
    like_count: 780,
    repost_count: 98,
    created_at: daysAgo(1),
  },
  {
    slug: "officiating-fitness-in-world-cup-tournament-heat",
    author_handle: "ref_klaas",
    author_display_name: "Klaas De Vries",
    author_role: "FIFA Referee",
    post_type: "discussion",
    content:
      "Officiating fitness in tournament heat is an overlooked World Cup variable. A referee covers 10–12km a match with repeated high-speed efforts to stay level with play. In Dallas afternoon heat, dehydration degrades decision latency before it degrades sprint speed — which is why match-control errors cluster late. Semi-automated offside tech helps, but positioning and recovery still decide the soft calls.",
    tags: ["#WorldCup2026", "#Officiating", "#SportsScience", "#MatchControl"],
    metrics: {
      distance_per_match_km: 11,
      high_speed_efforts: 48,
    },
    top_comments: [
      {
        comment_id: "c-007",
        author_handle: "amara_sc",
        author_display_name: "Amara Okafor",
        author_role: "Strength & Conditioning Coach",
        text: "Decision latency degrading before sprint speed is a key insight — same pattern we see in players. Pre-cooling vests between halves would help here too.",
        likes: 73,
        created_at: daysAgo(0),
      },
    ],
    like_count: 420,
    repost_count: 44,
    created_at: daysAgo(1),
  },
  {
    slug: "designing-a-high-press-that-survives-altitude",
    author_handle: "coach_lindqvist",
    author_display_name: "Erik Lindqvist",
    author_role: "Head Coach",
    post_type: "tactical_analysis",
    content:
      "Designing a high press that survives altitude: at 2,240m a full-pitch press is physiologically unaffordable for 90 minutes. Our adaptation for Mexico City is a mid-block with sharper, shorter triggers — we press in 6-second bursts on specific pass patterns rather than chasing continuously. Conditioning and tactics have to be designed as one system, never separately.",
    tags: ["#WorldCup2026", "#TacticalAnalysis", "#HighPress", "#AltitudeTraining"],
    metrics: {
      press_burst_duration_s: 6,
      target_elevation_m: 2240,
    },
    top_comments: [
      {
        comment_id: "c-008",
        author_handle: "marco_lowblock",
        author_display_name: "Marco Bianchi",
        author_role: "Tactical Analyst",
        text: "The 6-second burst press is the smart call. Continuous pressing at altitude just hands the opponent your transitions in the final 20 minutes.",
        likes: 96,
        created_at: daysAgo(0),
      },
      {
        comment_id: "c-009",
        author_handle: "elena_altitude",
        author_display_name: "Dr. Elena Vasquez",
        author_role: "Sports Scientist",
        text: "Designing conditioning and tactics as one system is exactly right. I can give you the oxygen-cost numbers per pressing scheme if useful.",
        likes: 134,
        created_at: daysAgo(0),
      },
    ],
    like_count: 1560,
    repost_count: 287,
    created_at: daysAgo(1),
  },
];
